# Generated by Django 5.0.2 on 2024-03-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
